<?php

return [
    'is_set_data_seed' => env('IS_SET_DATA_SEED'),
    'menu' => [
        'sidebar' => [
            [
                'name' => 'Главная страница',
                'url' => 'dashboard',
                'icon' => 'home',
                'position' => 1,
                'permission' => '',
                'active' => 'dashboard',
                'submenu' => [],
            ],
            [
                'name' => 'Администратор системы',
                'url' => '',
                'icon' => 'user-cog',
                'position' => 2,
                'permission' => [
                    'other.show_admin',
                    'other.show_committee',
                ],
                'active' => '',
                'submenu' => [
                    [
                        'name' => 'Список конкурсов',
                        'url' => 'contests',
                        'icon' => 'trophy',
                        'position' => 1,
                        'permission' => [
                            'other.show_admin',
                        ],
                        'active' => 'contests/*',
                        'submenu' => [],
                    ],
                    [
                        'name' => 'Список муниципальных образований',
                        'url' => 'municipalities',
                        'icon' => 'address-card',
                        'position' => 1,
                        'permission' => [
                            'other.show_admin',
                        ],
                        'active' => 'municipalities/*',
                        'submenu' => [],
                    ],
                    [
                        'name' => 'Реестр ТОС',
                        'url' => 'registers',
                        'icon' => 'address-card',
                        'position' => 2,
                        'permission' => [
                            'other.show_admin',
                        ],
                        'active' => 'registers/*',
                        'submenu' => [],
                    ],
                    [
                        'name' => 'Заявки "ППМИ"',
                        'url' => 'applications/ppmi',
                        'icon' => 'list-alt',
                        'position' => 3,
                        'permission' => [
                            'other.show_admin',
                            'other.show_committee',
                            'ppmi_application.view',
                        ],
                        'active' => 'applications/ppmi/*',
                        'submenu' => [],
                    ],
                    [
                        'name' => 'Заявки "Лучшее ТОС"',
                        'url' => 'applications/ltos',
                        'icon' => 'list-alt',
                        'position' => 4,
                        'permission' => [
                            'other.show_admin',
                            'other.show_committee',
                            'ltos_application.view',
                        ],
                        'active' => 'applications/ltos/*',
                        'submenu' => [],
                    ],
                    [
                        'name' => 'Заявки "Лучшая практика гражданских инициатив"',
                        'url' => 'applications/lptos',
                        'icon' => 'list-alt',
                        'position' => 5,
                        'permission' => [
                            'other.show_admin',
                            'other.show_committee',
                            'lptos_application.view',
                        ],
                        'active' => 'applications/lptos/*',
                        'submenu' => [],
                    ],
                    [
                        'name' => 'Заявки "Соц значимые проекты ТОС"',
                        'url' => 'applications/szptos',
                        'icon' => 'list-alt',
                        'position' => 6,
                        'permission' => [
                            'other.show_admin',
                            'other.show_committee',
                            'szptos_application.view',
                        ],
                        'active' => 'applications/szptos/*',
                        'submenu' => [],
                    ],
                    [
                        'name' => 'Заявки "Лучший специалист"',
                        'url' => 'applications/ls',
                        'icon' => 'list-alt',
                        'position' => 7,
                        'permission' => [
                            'other.show_admin',
                            'other.show_committee',
                            'ls_application.view',
                        ],
                        'active' => 'applications/ls/*',
                        'submenu' => [],
                    ],
                    [
                        'name' => 'Заявки "Самое красивое село"',
                        'url' => 'applications/most_beautiful_villages',
                        'icon' => 'list-alt',
                        'position' => 6,
                        'permission' => [
                            'other.show_admin',
                            'other.show_committee',
                            'most_beautiful_village.view',
                        ],
                        'active' => 'applications/most_beautiful_villages/*',
                        'submenu' => [],
                    ],
                ],
            ],
            [
                'name' => 'Представитель ППМИ',
                'url' => '',
                'icon' => 'user',
                'position' => 3,
                'permission' => [
                    'other.show_user',
                ],
                'active' => '',
                'submenu' => [
                    [
                        'name' => 'Мои заявки на конкурсы',
                        'url' => 'applications/ppmi',
                        'icon' => 'list-alt',
                        'position' => 1,
                        'permission' => [
                            'other.show_user',
                            'ppmi_application.view',
                        ],
                        'active' => 'applications/ppmi/*',
                        'submenu' => [],
                    ],
                ],
            ],
            [
                'name' => 'Представитель ТОС',
                'url' => '',
                'icon' => 'user',
                'position' => 4,
                'permission' => [
                    'other.show_user',
                ],
                'active' => '',
                'submenu' => [
                    [
                        'name' => 'Мои заявки "Лучшее ТОС"',
                        'url' => 'applications/ltos',
                        'icon' => 'list-alt',
                        'position' => 1,
                        'permission' => [
                            'other.show_user',
                            'ltos_application.view',
                        ],
                        'active' => 'applications/ltos/*',
                        'submenu' => [],
                    ],
                    [
                        'name' => 'Мои заявки "Социально значимые проекты"',
                        'url' => 'applications/szptos',
                        'icon' => 'list-alt',
                        'position' => 2,
                        'permission' => [
                            'other.show_user',
                            'szptos_application.view',
                        ],
                        'active' => 'applications/szptos/*',
                        'submenu' => [],
                    ],
                    [
                        'name' => 'Мои заявки "Лучшая практика"',
                        'url' => 'applications/lptos',
                        'icon' => 'list-alt',
                        'position' => 3,
                        'permission' => [
                            'other.show_user',
                            'lptos_application.view',
                        ],
                        'active' => 'applications/lptos/*',
                        'submenu' => [],
                    ],
                ],
            ],
            [
                'name' => 'Другие конкурсы',
                'url' => '',
                'icon' => 'user',
                'position' => 4,
                'permission' => [
                    'other.show_user',
                ],
                'active' => '',
                'submenu' => [
                    [
                        'name' => 'Заявки "Лучший специалист"',
                        'url' => 'applications/ls',
                        'icon' => 'list-alt',
                        'position' => 5,
                        'permission' => [
                            'other.show_user',
                            'ls_application.view',
                        ],
                        'active' => 'applications/ls/*',
                        'submenu' => [],
                    ],
                    [
                        'name' => 'Заявки "Самое красивое село"',
                        'url' => 'applications/most_beautiful_villages',
                        'icon' => 'list-alt',
                        'position' => 6,
                        'permission' => [
                            'other.show_user',
                            'most_beautiful_village.view',
                        ],
                        'active' => 'applications/most_beautiful_villages/*',
                        'submenu' => [],
                    ],
                ],
            ],
            [
                'name' => 'Портал ИБ',
                'url' => '',
                'icon' => 'book',
                'position' => 5,
                'permission' => [
                    'other.show_user',
                ],
                'active' => '',
                'submenu' => [
                    [
                        'name' => 'Добавить проект',
                        'url' => 'posts/create',
                        'icon' => 'plus',
                        'position' => 1,
                        'permission' => [
                            'other.show_user',
//                            'posts.view',
                        ],
                        'active' => 'posts/create',
                        'submenu' => [],
                    ],
                    [
                        'name' => 'Список проектов',
                        'url' => 'posts',
                        'icon' => 'list-alt',
                        'position' => 6,
                        'permission' => [
                            'other.show_user',
//                            'posts.view',
                        ],
                        'active' => 'posts/*',
                        'submenu' => [],
                    ],
                ],
            ],
            [
                'name' => 'Пользователи',
                'url' => '',
                'icon' => 'users',
                'position' => PHP_INT_MAX - 1,
                'permission' => 'user.view',
                'active' => 'users/*',
                'submenu' => [
                    [
                        'name' => 'Пользователи',
                        'url' => 'users',
                        'icon' => '',
                        'position' => 1,
                        'permission' => '',
                        'active' => 'users/*',
                        'submenu' => [],
                    ],
                    [
                        'name' => 'Роли',
                        'url' => 'roles',
                        'icon' => '',
                        'position' => 2,
                        'permission' => 'role.view',
                        'active' => 'roles/*',
                        'submenu' => [],
                    ],
                    [
                        'name' => 'Разрешения',
                        'url' => 'permissions',
                        'icon' => '',
                        'position' => 3,
                        'permission' => '',
                        'active' => 'permissions/*',
                        'submenu' => [],
                    ],
                ],
            ],
            [
                'name' => 'Инструкция по использованию',
                'url' => '//docs.init-rk.ru/',
                'icon' => 'book',
                'position' => PHP_INT_MAX - 1,
                'permission' => '',
                'active' => '',
                'submenu' => [],
            ],
        ],
    ],
    // Миниатюры
    "miniatures" => [
        "large" => [
            "width" => 960,
            "height" => 640,
            "crop" => false,
        ],
        "medium" => [
            "width" => 847,
            "height" => 424,
            "crop" => false,
        ],
        "small" => [
            "width" => 262,
            "height" => 166,
            "crop" => false,
        ],
        "thumbnail" => [
            "width" => 200,
            "height" => 200,
            "crop" => true,
        ],
    ],
    'app_name' => env('APP_NAME', ''),
    'yandex_map_token' => env('YANDEX_MAP_TOKEN', ''),
];
